# Generated by Django 3.1.5 on 2021-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_auto_20210120_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
